[package]
name = "user_config_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
once_cell = "1.8"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }